### ISSUE TITLE
prometheus container won't start

### ISSUE THREAD

**Issue by tvinhas** [vegasbrianc/github-monitoring#1]
The prometheus container fails to start:

prometheus    | time="2017-02-24T12:39:30Z" level=info msg="Starting prometheus (version=1.5.2, branch=master, revision=bd1182d29f462c39544f94cc822830e1c64cf55b)" source="main.go:75"
prometheus    | time="2017-02-24T12:39:30Z" level=info msg="Build context (go=go1.7.5, user=root@1a01c5f68840, date=20170210-16:23:28)" source="main.go:76"
prometheus    | time="2017-02-24T12:39:30Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:248"
prometheus    | time="2017-02-24T12:39:30Z" level=error msg="Error loading config: couldn't load configuration (-config.file=/etc/prometheus/prometheus.yml): open /etc/prometheus/prometheus.yml: no such file or directory" source="main.go:150"
prometheus exited with code 1

**Comment by vegasbrianc** [comment]
Hi @tvinhas Thanks for your message. Can I ask what Operating System you are using, versions of Docker, etc? I just ran this new once again on Docker for Mac and Ubuntu 16.04 without issues. 

Also, did you update the configs in anyway?

Thanks!
