### ISSUE TITLE
Datasource named ${DS_PROMETHEUS} was not found

### ISSUE THREAD

**Issue by sasanka-hl** [vegasbrianc/github-monitoring#10]
None of the panels show up, and all I see is this error.

![screen shot 2018-03-08 at 6 20 06 pm](https://user-images.githubusercontent.com/35507704/37187041-5b56b48a-22fd-11e8-93e6-70e171bde10f.png)

Any clue?

**Comment by vegasbrianc** [comment]
@sasanka-hl This should be fixed now. Pull the updated version. I hard-coded the datasource and dashboards to use the name prometheus which fixed the issue.  See 700ff45b8c75ba031ff2b70c3bfb06a8bec62058
