### ISSUE TITLE
Speedtest for global locations, and ICMP probe

### ISSUE THREAD

**Issue by ghost** [vegasbrianc/github-monitoring#16]
Hello,

Great tool, thanks for packaging it up.

I am wondering if you can help with two issues that I am experiencing:

1) Speedtest consistently shows low speed and high latency.  Is it possible that this is using a US-based node and if yes it is possible for me to configure the node manually?
2) Could you indicate how an ICMP probe may be added?  This is a workaround to a problem that I am facing; I want to be able to capture data points which show a failed HTTP probe, but I don't seem to be able to do this in Prometheus as rather than an event existing with a failure code no event exists.  I am considering that perhaps using an ICMP probe would show a failure event.

Thanks in advance.

**Comment by vegasbrianc** [comment]
Hi @efab9c6f2b4c49578f8e619e27f6b3fb I would recommend you to have a look at the [Blackbox Exporter ](https://github.com/prometheus/blackbox_exporter) This can be integrated the same as other exporters and will provide ICMP.

Let me know if you need further help or have questions.
