### ISSUE TITLE
Unable to add custom repo details

### ISSUE THREAD

**Issue by DirectedSoul1** [vegasbrianc/github-monitoring#17]
After editing the docker-compose.yml file with the repo details 

```
 environment:
      - REPOS=kubevirt/kubevirt
```
And importing the template, Im not seeing any stats and also the older REPO(docker/docker, freeCodeCamp/freeCodeCamp)  exists.

**Comment by DirectedSoul1** [comment]
Able to add custom repo by editing the `docker-compose.yaml` file. Is there a way to view the Contributors, Commits and PR's for the custom repo by editing the template?

**Comment by vegasbrianc** [comment]
Sorry, this somehow missed my inbox. Here's all the metrics available in the repo exporter - https://github.com/infinityworks/github-exporter/blob/master/METRICS.md
