### ISSUE TITLE
no data points

### ISSUE THREAD

**Issue by linlynn** [vegasbrianc/github-monitoring#4]
hi  , I am following this guide https://github.com/vegasbrianc/github-monitoring and no data points in github stats dashboard
go to http://localhost:9090/targets and shows

Endpoint | State | Labels | Last Scrape | Error
-- | -- | -- | -- | --
http://localhost:9090/metrics | up | instance="localhost:9090" | 14.744s ago |  
http://metrics:9171/metrics | up | instance="metrics:9171" | 7.262s ago |  
http://node-exporter:9100/metrics | down | instance="node-exporter:9100" | 14.295s ago | Get http://node-exporter:9100/metrics: dial tcp: lookup node-exporter on 127.0.0.11:53: server misbehaving

i also checked the date looks good

any idea ?

**Comment by vegasbrianc** [comment]
Hi @linlynn I removed node exporter from the targets as it is not used in this stack. Second, can you include the metric service `environment:` configuration of your docker-compose.yml file?

**Comment by linlynn** [comment]
@vegasbrianc  I am using the docker-compose file https://github.com/vegasbrianc/github-monitoring/blob/master/docker-compose.yml (update my token as suggested )

**Comment by vegasbrianc** [comment]
If you open http://0.0.0.0:9171/metrics do you see metrics?

**Comment by linlynn** [comment]
hi @vegasbrianc  can't access it 
Unable to connect

Firefox can’t establish a connection to the server at 0.0.0.0:9171.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

this is docker container running status

lynn@lynn-ThinkCentre-M92p:~/github-monitoring$ sudo docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                     NAMES
99906f31f103        grafana/grafana                        "/run.sh"                28 minutes ago      Up 28 minutes       0.0.0.0:3000->3000/tcp    githubmonitoring_grafana_1
997eab108102        prom/prometheus                        "/bin/prometheus -..."   28 minutes ago      Up 28 minutes       0.0.0.0:9090->9090/tcp    prometheus
44ab540ea290        infinityworks/github-exporter:latest   "/bin/main"              28 minutes ago      Up 28 minutes       9171/tcp                  githubmonitoring_metrics_1

**Comment by vegasbrianc** [comment]
HI @linlynn I updated the docker-compose.yml file. Can you please update your project with the latest version of the compose and then you should be able to access 0.0.0.0:9171

**Comment by linlynn** [comment]
Thx,Actually I already changed locally to expose port to host,I will try again today to see if I still see no data points

**Comment by linlynn** [comment]
@vegasbrianc  here is 9171 metrics

# HELP github_rate_limit Number of API queries allowed in a 60 minute window
# TYPE github_rate_limit gauge
github_rate_limit 5000
# HELP github_rate_remaining Number of API queries remaining in the current window
# TYPE github_rate_remaining gauge
github_rate_remaining 4791
# HELP github_rate_reset The time at which the current rate limit window resets in UTC epoch seconds
# TYPE github_rate_reset gauge
github_rate_reset 1.501817429e+09
# HELP github_repo_forks Total number of forks for given repository
# TYPE github_repo_forks gauge
github_repo_forks{private="false",repo="moby",user="moby"} 13303
# HELP github_repo_open_issues Total number of open issues for given repository
# TYPE github_repo_open_issues gauge
github_repo_open_issues{private="false",repo="moby",user="moby"} 2787
# HELP github_repo_size_kb Size in KB for given repository
# TYPE github_repo_size_kb gauge
github_repo_size_kb{private="false",repo="moby",user="moby"} 132469
# HELP github_repo_stars Total number of Stars for given repository
# TYPE github_repo_stars gauge
github_repo_stars{private="false",repo="moby",user="moby"} 44853
# HELP github_repo_watchers Total number of watchers/subscribers for given repository
# TYPE github_repo_watchers gauge
github_repo_watchers{private="false",repo="moby",user="moby"} 3274
# HELP go_gc_duration_seconds A summary of the GC invocation durations.

**Comment by vegasbrianc** [comment]
Hi @linlynn I saw an update from you today about the metrics. Were you able to make any progress? Can you see the data now in Grafana?

**Comment by linlynn** [comment]
hi @vegasbrianc  i made another pr to make it work for multiple repositories ,please take a look 
https://github.com/vegasbrianc/github-monitoring/pull/6
