### ISSUE TITLE
Unsupported config option for services service: 'metrics'

### ISSUE THREAD

**Issue by Aman-Osman-Bose** [vegasbrianc/github-monitoring#8]
I am getting this:
$ docker-compose up -d
Unsupported config option for services service: 'metrics'

** running docker version
Server Version: 17.09.1-ce

** docker-compose -version
docker-compose version: 1.4.0

**Comment by vegasbrianc** [comment]
@Aman-Osman-Bose Apologies for this taking so long. I updated the stack today with all the latest components. It should be good to go. Let me know if you have any further issues.
